// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ajfekrrllgmbuccddotm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFqZmVrcnJsbGdtYnVjY2Rkb3RtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE2NDQ2NTIsImV4cCI6MjA1NzIyMDY1Mn0.5SHCGdWRrf2hnEWtmt-9fAHM3aKAVP8PBh8mFPkweVs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);